fix: Add check for requirements.txt

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -11,6 +11,14 @@ parts:
       - pkg-config
       - rustc
       - cargo
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
+
 bases:
   - build-on:
     - name: "ubuntu"
